---
# tasks file for node1
  - name: include vars
    include_vars: "../../vars.yml"

#we start the docker container with all the parameters we have
  - name: create the container
    docker_container:
      name: "{{ name_host1 }}"
      detach: yes
      image: "{{ imagename }}:{{ tagname }}"
      hostname: "{{ name_host1 }}"
      state: started
      env:
        RABBITMQ_NODENAME: "{{ rabbit_node1 }}"
      published_ports:
        - "4369:4369"
        - "5671:5671"
        - "5672:5672"
        - "25672:25672"
        - "35672:35672"
   
  #We need to set up the cookie
  - name: change erlang cookie value
    command: docker exec {{ name_host1 }} /bin/bash -c "echo {{ mycookie }} > /var/lib/rabbitmq/.erlang.cookie"
    
  #after changing the cookie we need to restart the container
  - name: restart rabbit1 container
    docker_container:
      name: rabbit1
      image: "{{ imagename }}:{{ tagname }}"
      state: started 
      restart: yes
  