---
# tasks file for node3
#we start the docker container with all the parameters we have
    # tasks file for node1
    - name: include vars
      include_vars: "../../vars.yml"
    
    - name: create the container
      docker_container:
        name: "{{ name_host3 }}"
        detach: yes
        image: "{{ imagename }}:{{ tagname }}"
        hostname: "{{ name_host3 }}"
        state: started
        env:
          RABBITMQ_NODENAME: "{{ rabbit_node3 }}"
        etc_hosts: >
          {  
            "{{ name_host1 }}": "{{ rabbit1_ip }}",
            "{{ name_host2 }}": "{{ rabbit2_ip }}"
          } 
        published_ports:
          - "4369:4369"
          - "5671:5671"
          - "5672:5672"
          - "25672:25672"
          - "35672:35672"
   
    #We need to set up the cookie
    - name: change erlang cookie value
      command: docker exec {{ name_host3 }} /bin/bash -c "echo {{ mycookie }} > /var/lib/rabbitmq/.erlang.cookie"
    
    #after changing the cookie we need to restart the container
    - name: restart rabbit3 container
      docker_container:
        name: "{{ name_host3 }}"
        image: "{{ imagename }}:{{ tagname }}"
        state: started
        restart: yes

    #now we can tell it to cluster with node 1
    - name: stop rabbitmqctl 
      command: docker exec {{ name_host3 }} /bin/bash -c "rabbitmqctl stop_app"
    
    #we reset the rabbitmqctl service
    - name: reset rabbitmqctl
      command: docker exec {{ name_host3 }} /bin/bash -c "rabbitmqctl reset"
    
    #we join the node2 with node1
    - name: cluster join
      command: docker exec {{ name_host3 }} /bin/bash -c "rabbitmqctl join_cluster {{ rabbit_node1 }}@{{ name_host1 }}"
    
    #we start the app again
    - name: start rabbitmqctl app
      command: docker exec {{ name_host3 }} /bin/bash -c "rabbitmqctl start_app"
    
    #we show the cluster status
    - name: status of cluster
      command: docker exec {{ name_host3 }} /bin/bash -c "rabbitmqctl cluster_status"
      register: msgcluster
    - debug: msg="{{ msgcluster.stdout }}"

    #print docker-ce and rabbitmq package version
    - name: docker-ce ver
      command: dpkg -s docker-ce
      register: msgdocker
    - debug: msg="{{ msgdocker.stdout_lines }}"

    - name: rabbitmq-server
      command: docker exec {{ name_host3 }} /bin/bash -c "dpkg -s rabbitmq-server"
      register: msgrabbit
    - debug: msg="{{ msgrabbit.stdout_lines }}"