---
# tasks file for node2
# tasks file for node1
    - name: include vars
      include_vars: "../../vars.yml"

#we start the docker container with all the parameters we have
    - name: create the container
      docker_container:
        name: "{{ name_host2 }}"
        detach: yes
        image: "{{ imagename }}:{{ tagname }}"
        hostname: "{{ name_host2 }}"
        state: started
        env:
          RABBITMQ_NODENAME: "{{ rabbit_node2 }}"
        published_ports:
          - "4369:4369"
          - "5671:5671"
          - "5672:5672"
          - "25672:25672"
          - "35672:35672"
   
    #We need to set up the cookie
    - name: change erlang cookie value
      command: docker exec {{ name_host2 }} /bin/bash -c "echo {{ mycookie }} > /var/lib/rabbitmq/.erlang.cookie"
    
    #after changing the cookie we need to restart the container
    - name: restart rabbit2 container
      docker_container:
        name: "{{ name_host2 }}"
        image: "{{ imagename }}:{{ tagname }}"
        state: started 
        restart: yes


    #we need to add the instance1 ip as host in the container
    - name: add host
      command: docker exec {{ name_host2 }} /bin/bash -c "echo {{ rabbit1_ip }} {{ name_host1 }} >> /etc/hosts"

    #now we can tell it to cluster with node 1
    - name: stop rabbitmqctl 
      command: docker exec {{ name_host2 }} /bin/bash -c "rabbitmqctl stop_app"
    
    #we reset the rabbitmqctl service
    - name: reset rabbitmqctl
      command: docker exec {{ name_host2 }} /bin/bash -c "rabbitmqctl reset"
    
    #we join the node2 with node1
    - name: cluster join
      command: docker exec {{ name_host2 }} /bin/bash -c "rabbitmqctl join_cluster {{ rabbit_node1 }}@{{ name_host1 }}"
    
    #we start the app again
    - name: start rabbitmqctl app
      command: docker exec {{ name_host2 }} /bin/bash -c "rabbitmqctl start_app"
    
    #we show the cluster status
    - name: status of cluster
      command: docker exec {{ name_host2 }} /bin/bash -c "rabbitmqctl cluster_status"
