---
# tasks file for common

    #we include the vars used for all the playbooks
    - name: include vars
      include_vars: "../../vars.yml"
    
    #we follow all the steps taken in order to install docker-ce from the official page
    - name: install packages needed for docker
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python-pip
    
    - name: add docker GPG key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present
    
    - name: add docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      
    - name: install docker-ce
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - docker-ce
    
    #we use pip install to install the docker module for ansible
    - name: install docker-py for ansible docker module
      pip:
        name: "{{ item }}"
        state: latest
      with_items:
        - docker
    
    #we copy the git repository with the dockerfile into the instance
    - name: copy git repository with the dockerfile to the instance
      git:
        repo: https://github.com/ArashiJF/cluster-rabbitmq.git
        dest: /home/ubuntu/ansiblerabbitnodes
        version: master
    
    #build the docker image with ubuntu xenial and rabbitmq-server
    - name: build docker image
      docker_image: name={{ imagename }} tag={{ tagname }} path=/home/ubuntu/ansiblerabbitnodes state=present
    